"""initial schema

Revision ID: ce149a78d2f7
Revises: 
Create Date: 2026-09-08 11:13:34.562615
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce149a78d2f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=300), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('cta', sa.String(length=200), nullable=False),
    sa.Column('brand_colors', sa.JSON(), nullable=False),
    sa.Column('logo_b2_key', sa.String(length=500), nullable=True),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.Enum('QUICK', 'FULL', name='runmode'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'STORYBOARD', 'SUCCEEDED', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_snapshot', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('manifest_b2_key', sa.String(length=500), nullable=True),
    sa.Column('canonical_hash', sa.String(length=128), nullable=True),
    sa.Column('genblaze_run_id', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'FINAL', 'MANIFEST', 'OTHER', name='assetkind'), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('sha256', sa.String(length=128), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('thumbnail_b2_key', sa.String(length=500), nullable=True),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_run_id'))
        batch_op.drop_index(batch_op.f('ix_assets_campaign_id'))

    op.drop_table('assets')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_campaign_id'))

    op.drop_table('runs')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
